### PR TITLE
upgraded to dune 2.0, fixed cross-compilation

### PR DESCRIPTION
**Pull request by nandor**
Upgraded to dune 2.0. The new rules should support cross-compilation and environments with no shared libraries.

Tested by pinning `eigen`, installing it, building owl and running its unit tests using `dune runtest`.

It would be great if someone else could also test these changes as I am not an active user of owl/eigen.

### CODE REVIEW

**Comment by mseri** [comment]
Thank you very much! I’ll have a look as soon as possible, and test it on private branches of owl and owl_ode to double check

**Comment by mseri** [comment]
Works on my laptop with osx. Testing also on a larger travis matrix before merging.

**Comment by mseri** [comment]
Mmh, many builds are failing due to excessive logs. I don’t understand if is something with the compiler, the flags or if they are harmless logs. See for example https://travis-ci.org/mseri/owl/jobs/623753631

**Comment by mseri** [comment]
Looks like it works well despite the long logs: https://github.com/ocaml/opam-repository/pull/15518

**Comment by mseri** [comment]
Thanks for the help!

**Comment by nandor** [comment]
Thanks for merging! I was wondering if you are planning to bump the opam version anytime soon?

**Comment by mseri** [comment]
In which sense? I am already releasing this change in opam-repository

**Pull request merged**
